[2024-06-04T15:18:45.427+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T15:18:45.474+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_tables.task_create_tb_weather manual__2024-06-04T15:14:08.245095+00:00 [queued]>
[2024-06-04T15:18:45.489+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_tables.task_create_tb_weather manual__2024-06-04T15:14:08.245095+00:00 [queued]>
[2024-06-04T15:18:45.490+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-04T15:18:45.514+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): task_create_tb_weather> on 2024-06-04 15:14:08.245095+00:00
[2024-06-04T15:18:45.527+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=461) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-04T15:18:45.530+0000] {standard_task_runner.py:63} INFO - Started process 463 to run task
[2024-06-04T15:18:45.529+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'create_tables', 'task_create_tb_weather', 'manual__2024-06-04T15:14:08.245095+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/create_tables.py', '--cfg-path', '/tmp/tmpqx743i7z']
[2024-06-04T15:18:45.534+0000] {standard_task_runner.py:91} INFO - Job 52: Subtask task_create_tb_weather
[2024-06-04T15:18:45.595+0000] {task_command.py:426} INFO - Running <TaskInstance: create_tables.task_create_tb_weather manual__2024-06-04T15:14:08.245095+00:00 [running]> on host 6b740a15ab9e
[2024-06-04T15:18:45.694+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Matheus' AIRFLOW_CTX_DAG_ID='create_tables' AIRFLOW_CTX_TASK_ID='task_create_tb_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T15:14:08.245095+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T15:14:08.245095+00:00'
[2024-06-04T15:18:45.697+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T15:18:45.698+0000] {sql.py:276} INFO - Executing: 
CREATE TABLE IF NOT EXISTS tb_weather 
(Description VARCHAR(250) NOT NULL,
 Temperature double precision NOT NULL,
 Humidity integer NOT NULL,
 Wind_Speed double precision NOT NULL,
 Time timestamp without time zone NOT NULL,
 Clouds integer NOT NULL,
 Location VARCHAR(250) NOT NULL
 );
 
[2024-06-04T15:18:45.710+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-06-04T15:18:45.726+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-06-04T15:18:45.796+0000] {sql.py:470} INFO - Running statement: 
CREATE TABLE IF NOT EXISTS tb_weather 
(Description VARCHAR(250) NOT NULL,
 Temperature double precision NOT NULL,
 Humidity integer NOT NULL,
 Wind_Speed double precision NOT NULL,
 Time timestamp without time zone NOT NULL,
 Clouds integer NOT NULL,
 Location VARCHAR(250) NOT NULL
 );
 , parameters: None
[2024-06-04T15:18:45.828+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T15:18:45.843+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=create_tables, task_id=task_create_tb_weather, run_id=manual__2024-06-04T15:14:08.245095+00:00, execution_date=20240604T151408, start_date=20240604T151845, end_date=20240604T151845
[2024-06-04T15:18:45.867+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-04T15:18:45.890+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-04T15:18:45.894+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
